### ISSUE TITLE
geting this error

### ISSUE THREAD

**Issue by vivesh1** [Yichen-Dou/OC-Blender-Helper-Addon#3]
Traceback (most recent call last):
  File "C:\Program Files\BlenderOctane\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Vivesh\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Octane_Helper\__init__.py", line 19, in <module>
    from . operators import register_operators, unregister_operators
  File "C:\Users\Vivesh\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Octane_Helper\operators\__init__.py", line 2, in <module>
    from .environments import *
  File "C:\Users\Vivesh\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Octane_Helper\operators\environments.py", line 6, in <module>
    env_path = os.path.join(bpy.utils.preset_paths('octane')[0], 'environments')
IndexError: list index out of range

**Comment by Yichen-Dou** [comment]
Caused by missing presets folder which should be created by Blender automatically. Portable Blender version? And make sure you opened the Octane Blender, not the regular Blender

**Comment by Yichen-Dou** [comment]
Wait a minute... Your issue had been fixed a long time ago. This line of code even doesn't exist in the current project. Lol please use the newest one
